language: python
python:
  - "3.5"
env:
  - SECRET_KEY=TopSecretKey DEBUG=True ALLOWED_HOSTS=127.0.0.1
    EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
    EMAIL_HOST=localhost EMAIL_PORT=25 EMAIL_USE_TLS=False
    EMAIL_HOST_USER='' EMAIL_HOST_PASSWORD=''
install:
  - pip install -r requirements.txt
script:
  - python manage.py check
  - python manage.py test
