language: python
python:
  - "3.5"
env:
  - SECRET_KEY=TopSecretKey DEBUG=True ALLOWED_HOSTS=127.0.0.1
install:
  - pip install -r requirements.txt
script:
  - python manage.py check
  - python manage.py test
